// Silver Maid ERP - Mock Data
// Realistic data for development and testing

import {
  User,
  Staff,
  StaffAvailability,
  Customer,
  CustomerAddress,
  Service,
  Booking,
  BookingStaff,
  Invoice,
  DashboardStats,
  ConflictAlert,
} from '@/types';
import { addDays, subDays, startOfDay, format } from 'date-fns';

// ============================================
// HELPER FUNCTIONS
// ============================================

const today = startOfDay(new Date());

function generateId(): string {
  return Math.random().toString(36).substring(2, 15);
}

// ============================================
// USERS
// ============================================

export const mockUsers: User[] = [
  {
    id: 'user_admin_1',
    email: 'admin@silvermaid.ae',
    name: 'Ahmed Al Rashid',
    role: 'ADMIN',
    image: null,
    createdAt: subDays(today, 365),
    updatedAt: today,
    deletedAt: null,
  },
  {
    id: 'user_manager_1',
    email: 'sarah@silvermaid.ae',
    name: 'Sarah Johnson',
    role: 'MANAGER',
    image: null,
    createdAt: subDays(today, 200),
    updatedAt: today,
    deletedAt: null,
  },
  {
    id: 'user_staff_1',
    email: 'fatima@silvermaid.ae',
    name: 'Fatima Hassan',
    role: 'STAFF',
    image: null,
    createdAt: subDays(today, 150),
    updatedAt: today,
    deletedAt: null,
  },
  {
    id: 'user_staff_2',
    email: 'maria@silvermaid.ae',
    name: 'Maria Santos',
    role: 'STAFF',
    image: null,
    createdAt: subDays(today, 120),
    updatedAt: today,
    deletedAt: null,
  },
  {
    id: 'user_staff_3',
    email: 'priya@silvermaid.ae',
    name: 'Priya Sharma',
    role: 'STAFF',
    image: null,
    createdAt: subDays(today, 90),
    updatedAt: today,
    deletedAt: null,
  },
  {
    id: 'user_staff_4',
    email: 'anna@silvermaid.ae',
    name: 'Anna Rodriguez',
    role: 'STAFF',
    image: null,
    createdAt: subDays(today, 60),
    updatedAt: today,
    deletedAt: null,
  },
];

// ============================================
// STAFF
// ============================================

export const mockStaff: Staff[] = [
  {
    id: 'staff_1',
    userId: 'user_staff_1',
    employeeId: 'SM-001',
    phone: '+971501234567',
    emergencyContact: '+971509876543',
    address: 'Al Nahda, Sharjah',
    skills: ['RESIDENTIAL', 'DEEP_CLEAN', 'CARPET_CLEANING'],
    hourlyRate: 45,
    isActive: true,
    hireDate: subDays(today, 150),
    terminatedAt: null,
    notes: 'Excellent attention to detail. Prefers morning shifts.',
    createdAt: subDays(today, 150),
    updatedAt: today,
    deletedAt: null,
    user: mockUsers.find(u => u.id === 'user_staff_1'),
  },
  {
    id: 'staff_2',
    userId: 'user_staff_2',
    employeeId: 'SM-002',
    phone: '+971502345678',
    emergencyContact: '+971508765432',
    address: 'Al Qusais, Dubai',
    skills: ['RESIDENTIAL', 'COMMERCIAL', 'WINDOW_CLEANING'],
    hourlyRate: 50,
    isActive: true,
    hireDate: subDays(today, 120),
    terminatedAt: null,
    notes: 'Team leader material. Great with commercial clients.',
    createdAt: subDays(today, 120),
    updatedAt: today,
    deletedAt: null,
    user: mockUsers.find(u => u.id === 'user_staff_2'),
  },
  {
    id: 'staff_3',
    userId: 'user_staff_3',
    employeeId: 'SM-003',
    phone: '+971503456789',
    emergencyContact: '+971507654321',
    address: 'International City, Dubai',
    skills: ['RESIDENTIAL', 'DEEP_CLEAN', 'MOVE_IN_OUT'],
    hourlyRate: 48,
    isActive: true,
    hireDate: subDays(today, 90),
    terminatedAt: null,
    notes: 'Very efficient. Handles move-in/out cleanings well.',
    createdAt: subDays(today, 90),
    updatedAt: today,
    deletedAt: null,
    user: mockUsers.find(u => u.id === 'user_staff_3'),
  },
  {
    id: 'staff_4',
    userId: 'user_staff_4',
    employeeId: 'SM-004',
    phone: '+971504567890',
    emergencyContact: '+971506543210',
    address: 'Al Karama, Dubai',
    skills: ['COMMERCIAL', 'POST_CONSTRUCTION', 'DEEP_CLEAN'],
    hourlyRate: 55,
    isActive: true,
    hireDate: subDays(today, 60),
    terminatedAt: null,
    notes: 'Specialized in post-construction. Reliable.',
    createdAt: subDays(today, 60),
    updatedAt: today,
    deletedAt: null,
    user: mockUsers.find(u => u.id === 'user_staff_4'),
  },
];

// ============================================
// STAFF AVAILABILITY
// ============================================

export const mockStaffAvailability: StaffAvailability[] = [
  // Fatima - Sunday to Thursday
  { id: 'avail_1', staffId: 'staff_1', dayOfWeek: 0, startTime: '08:00', endTime: '17:00', isActive: true },
  { id: 'avail_2', staffId: 'staff_1', dayOfWeek: 1, startTime: '08:00', endTime: '17:00', isActive: true },
  { id: 'avail_3', staffId: 'staff_1', dayOfWeek: 2, startTime: '08:00', endTime: '17:00', isActive: true },
  { id: 'avail_4', staffId: 'staff_1', dayOfWeek: 3, startTime: '08:00', endTime: '17:00', isActive: true },
  { id: 'avail_5', staffId: 'staff_1', dayOfWeek: 4, startTime: '08:00', endTime: '17:00', isActive: true },
  
  // Maria - Sunday to Thursday
  { id: 'avail_6', staffId: 'staff_2', dayOfWeek: 0, startTime: '09:00', endTime: '18:00', isActive: true },
  { id: 'avail_7', staffId: 'staff_2', dayOfWeek: 1, startTime: '09:00', endTime: '18:00', isActive: true },
  { id: 'avail_8', staffId: 'staff_2', dayOfWeek: 2, startTime: '09:00', endTime: '18:00', isActive: true },
  { id: 'avail_9', staffId: 'staff_2', dayOfWeek: 3, startTime: '09:00', endTime: '18:00', isActive: true },
  { id: 'avail_10', staffId: 'staff_2', dayOfWeek: 4, startTime: '09:00', endTime: '18:00', isActive: true },
  
  // Priya - Monday to Saturday
  { id: 'avail_11', staffId: 'staff_3', dayOfWeek: 1, startTime: '07:00', endTime: '16:00', isActive: true },
  { id: 'avail_12', staffId: 'staff_3', dayOfWeek: 2, startTime: '07:00', endTime: '16:00', isActive: true },
  { id: 'avail_13', staffId: 'staff_3', dayOfWeek: 3, startTime: '07:00', endTime: '16:00', isActive: true },
  { id: 'avail_14', staffId: 'staff_3', dayOfWeek: 4, startTime: '07:00', endTime: '16:00', isActive: true },
  { id: 'avail_15', staffId: 'staff_3', dayOfWeek: 5, startTime: '08:00', endTime: '14:00', isActive: true },
  { id: 'avail_16', staffId: 'staff_3', dayOfWeek: 6, startTime: '08:00', endTime: '14:00', isActive: true },
  
  // Anna - Sunday to Thursday
  { id: 'avail_17', staffId: 'staff_4', dayOfWeek: 0, startTime: '10:00', endTime: '19:00', isActive: true },
  { id: 'avail_18', staffId: 'staff_4', dayOfWeek: 1, startTime: '10:00', endTime: '19:00', isActive: true },
  { id: 'avail_19', staffId: 'staff_4', dayOfWeek: 2, startTime: '10:00', endTime: '19:00', isActive: true },
  { id: 'avail_20', staffId: 'staff_4', dayOfWeek: 3, startTime: '10:00', endTime: '19:00', isActive: true },
  { id: 'avail_21', staffId: 'staff_4', dayOfWeek: 4, startTime: '10:00', endTime: '19:00', isActive: true },
];

// ============================================
// SERVICES
// ============================================

export const mockServices: Service[] = [
  {
    id: 'service_1',
    name: 'Regular Cleaning',
    description: 'Standard cleaning service for residential homes. Includes dusting, vacuuming, mopping, and bathroom cleaning.',
    basePrice: 150,
    priceUnit: 'flat',
    durationMinutes: 120,
    minCrewSize: 1,
    maxCrewSize: 2,
    requiredSkills: ['RESIDENTIAL'],
    vatRate: 5,
    isActive: true,
    sortOrder: 1,
    createdAt: subDays(today, 365),
    updatedAt: today,
    deletedAt: null,
  },
  {
    id: 'service_2',
    name: 'Deep Cleaning',
    description: 'Thorough deep cleaning service. Includes all regular cleaning plus detailed cleaning of appliances, cabinets, and hard-to-reach areas.',
    basePrice: 350,
    priceUnit: 'flat',
    durationMinutes: 240,
    minCrewSize: 2,
    maxCrewSize: 3,
    requiredSkills: ['DEEP_CLEAN'],
    vatRate: 5,
    isActive: true,
    sortOrder: 2,
    createdAt: subDays(today, 365),
    updatedAt: today,
    deletedAt: null,
  },
  {
    id: 'service_3',
    name: 'Move-In/Move-Out',
    description: 'Complete cleaning for properties before moving in or after moving out. Ensures the space is spotless.',
    basePrice: 500,
    priceUnit: 'flat',
    durationMinutes: 300,
    minCrewSize: 2,
    maxCrewSize: 4,
    requiredSkills: ['MOVE_IN_OUT', 'DEEP_CLEAN'],
    vatRate: 5,
    isActive: true,
    sortOrder: 3,
    createdAt: subDays(today, 365),
    updatedAt: today,
    deletedAt: null,
  },
  {
    id: 'service_4',
    name: 'Commercial Office',
    description: 'Professional cleaning for office spaces. Includes workstations, meeting rooms, and common areas.',
    basePrice: 75,
    priceUnit: 'hourly',
    durationMinutes: 180,
    minCrewSize: 2,
    maxCrewSize: 4,
    requiredSkills: ['COMMERCIAL'],
    vatRate: 5,
    isActive: true,
    sortOrder: 4,
    createdAt: subDays(today, 365),
    updatedAt: today,
    deletedAt: null,
  },
  {
    id: 'service_5',
    name: 'Carpet Cleaning',
    description: 'Professional carpet and rug cleaning using steam cleaning technology.',
    basePrice: 15,
    priceUnit: 'per_sqm',
    durationMinutes: 120,
    minCrewSize: 1,
    maxCrewSize: 2,
    requiredSkills: ['CARPET_CLEANING'],
    vatRate: 5,
    isActive: true,
    sortOrder: 5,
    createdAt: subDays(today, 365),
    updatedAt: today,
    deletedAt: null,
  },
  {
    id: 'service_6',
    name: 'Window Cleaning',
    description: 'Interior and exterior window cleaning for residential and commercial properties.',
    basePrice: 200,
    priceUnit: 'flat',
    durationMinutes: 90,
    minCrewSize: 1,
    maxCrewSize: 2,
    requiredSkills: ['WINDOW_CLEANING'],
    vatRate: 5,
    isActive: true,
    sortOrder: 6,
    createdAt: subDays(today, 365),
    updatedAt: today,
    deletedAt: null,
  },
  {
    id: 'service_7',
    name: 'Post-Construction',
    description: 'Specialized cleaning after construction or renovation. Removes dust, debris, and construction residue.',
    basePrice: 800,
    priceUnit: 'flat',
    durationMinutes: 480,
    minCrewSize: 3,
    maxCrewSize: 6,
    requiredSkills: ['POST_CONSTRUCTION'],
    vatRate: 5,
    isActive: true,
    sortOrder: 7,
    createdAt: subDays(today, 365),
    updatedAt: today,
    deletedAt: null,
  },
];

// ============================================
// CUSTOMERS
// ============================================

export const mockCustomers: Customer[] = [
  {
    id: 'cust_1',
    type: 'RESIDENTIAL',
    name: 'Mohammed Al Maktoum',
    email: 'mohammed.maktoum@email.com',
    phone: '+971551234567',
    companyName: null,
    taxId: null,
    notes: 'VIP customer. Prefers same cleaning team each visit.',
    preferences: JSON.stringify({ preferredTime: 'morning', allergies: ['strong chemicals'] }),
    isActive: true,
    createdAt: subDays(today, 300),
    updatedAt: today,
    deletedAt: null,
  },
  {
    id: 'cust_2',
    type: 'RESIDENTIAL',
    name: 'Emily Thompson',
    email: 'emily.t@email.com',
    phone: '+971552345678',
    companyName: null,
    taxId: null,
    notes: 'Has two cats. Need to be careful with doors.',
    preferences: JSON.stringify({ preferredTime: 'afternoon', pets: true }),
    isActive: true,
    createdAt: subDays(today, 250),
    updatedAt: today,
    deletedAt: null,
  },
  {
    id: 'cust_3',
    type: 'COMMERCIAL',
    name: 'TechStart Solutions',
    email: 'office@techstart.ae',
    phone: '+971553456789',
    companyName: 'TechStart Solutions LLC',
    taxId: 'TRN100123456789',
    notes: 'Weekly cleaning contract. Access code: 4521',
    preferences: JSON.stringify({ preferredTime: 'after_hours', accessCode: '4521' }),
    isActive: true,
    createdAt: subDays(today, 200),
    updatedAt: today,
    deletedAt: null,
  },
  {
    id: 'cust_4',
    type: 'RESIDENTIAL',
    name: 'Aisha Khan',
    email: 'aisha.khan@email.com',
    phone: '+971554567890',
    companyName: null,
    taxId: null,
    notes: 'Prefers female cleaning staff only.',
    preferences: JSON.stringify({ preferredTime: 'morning', femaleStaffOnly: true }),
    isActive: true,
    createdAt: subDays(today, 150),
    updatedAt: today,
    deletedAt: null,
  },
  {
    id: 'cust_5',
    type: 'COMMERCIAL',
    name: 'Dubai Design Studio',
    email: 'hello@dubaidesign.ae',
    phone: '+971555678901',
    companyName: 'Dubai Design Studio FZ-LLC',
    taxId: 'TRN100234567890',
    notes: 'Sensitive equipment. Extra care needed.',
    preferences: JSON.stringify({ preferredTime: 'weekend', sensitiveEquipment: true }),
    isActive: true,
    createdAt: subDays(today, 100),
    updatedAt: today,
    deletedAt: null,
  },
  {
    id: 'cust_6',
    type: 'RESIDENTIAL',
    name: 'James Wilson',
    email: 'james.wilson@email.com',
    phone: '+971556789012',
    companyName: null,
    taxId: null,
    notes: null,
    preferences: null,
    isActive: true,
    createdAt: subDays(today, 50),
    updatedAt: today,
    deletedAt: null,
  },
  {
    id: 'cust_7',
    type: 'RESIDENTIAL',
    name: 'Sara Abdullah',
    email: 'sara.a@email.com',
    phone: '+971557890123',
    companyName: null,
    taxId: null,
    notes: 'New villa, needs deep clean first then regular service.',
    preferences: JSON.stringify({ preferredTime: 'morning' }),
    isActive: true,
    createdAt: subDays(today, 30),
    updatedAt: today,
    deletedAt: null,
  },
  {
    id: 'cust_8',
    type: 'COMMERCIAL',
    name: 'Marina Fitness Center',
    email: 'manager@marinafitness.ae',
    phone: '+971558901234',
    companyName: 'Marina Fitness LLC',
    taxId: 'TRN100345678901',
    notes: 'Daily cleaning required. High traffic facility.',
    preferences: JSON.stringify({ preferredTime: 'early_morning' }),
    isActive: true,
    createdAt: subDays(today, 20),
    updatedAt: today,
    deletedAt: null,
  },
];

// ============================================
// CUSTOMER ADDRESSES
// ============================================

export const mockAddresses: CustomerAddress[] = [
  {
    id: 'addr_1',
    customerId: 'cust_1',
    label: 'Home',
    street: 'Palm Jumeirah, Frond A',
    building: 'Villa 15',
    floor: null,
    apartment: null,
    area: 'Palm Jumeirah',
    city: 'Dubai',
    emirate: 'Dubai',
    country: 'UAE',
    coordinates: '25.1124,55.1390',
    notes: 'Security gate requires advance notice. Call on arrival.',
    isPrimary: true,
    createdAt: subDays(today, 300),
    updatedAt: today,
  },
  {
    id: 'addr_2',
    customerId: 'cust_2',
    label: 'Apartment',
    street: 'Sheikh Zayed Road',
    building: 'Emirates Towers',
    floor: '42',
    apartment: '4215',
    area: 'Trade Centre',
    city: 'Dubai',
    emirate: 'Dubai',
    country: 'UAE',
    coordinates: '25.2176,55.2780',
    notes: 'Parking in B2. Use service elevator.',
    isPrimary: true,
    createdAt: subDays(today, 250),
    updatedAt: today,
  },
  {
    id: 'addr_3',
    customerId: 'cust_3',
    label: 'Office',
    street: 'Business Bay',
    building: 'Bay Square',
    floor: '8',
    apartment: '805',
    area: 'Business Bay',
    city: 'Dubai',
    emirate: 'Dubai',
    country: 'UAE',
    coordinates: '25.1857,55.2620',
    notes: 'Reception has key. Clean after 6 PM.',
    isPrimary: true,
    createdAt: subDays(today, 200),
    updatedAt: today,
  },
  {
    id: 'addr_4',
    customerId: 'cust_4',
    label: 'Villa',
    street: 'Arabian Ranches 2',
    building: 'Villa 78',
    floor: null,
    apartment: null,
    area: 'Arabian Ranches',
    city: 'Dubai',
    emirate: 'Dubai',
    country: 'UAE',
    coordinates: '25.0514,55.2688',
    notes: 'Has a maid room that also needs cleaning.',
    isPrimary: true,
    createdAt: subDays(today, 150),
    updatedAt: today,
  },
  {
    id: 'addr_5',
    customerId: 'cust_5',
    label: 'Studio',
    street: 'Dubai Design District',
    building: 'D3 Building 5',
    floor: '2',
    apartment: '201',
    area: 'Dubai Design District',
    city: 'Dubai',
    emirate: 'Dubai',
    country: 'UAE',
    coordinates: '25.1856,55.2972',
    notes: 'Expensive artwork and equipment. Use provided cleaning supplies.',
    isPrimary: true,
    createdAt: subDays(today, 100),
    updatedAt: today,
  },
  {
    id: 'addr_6',
    customerId: 'cust_6',
    label: 'Apartment',
    street: 'JBR Walk',
    building: 'Rimal 4',
    floor: '15',
    apartment: '1502',
    area: 'Jumeirah Beach Residence',
    city: 'Dubai',
    emirate: 'Dubai',
    country: 'UAE',
    coordinates: '25.0792,55.1342',
    notes: null,
    isPrimary: true,
    createdAt: subDays(today, 50),
    updatedAt: today,
  },
  {
    id: 'addr_7',
    customerId: 'cust_7',
    label: 'New Villa',
    street: 'Dubai Hills Estate',
    building: 'Villa 234',
    floor: null,
    apartment: null,
    area: 'Dubai Hills',
    city: 'Dubai',
    emirate: 'Dubai',
    country: 'UAE',
    coordinates: '25.1029,55.2456',
    notes: 'Under construction nearby. May need post-construction cleaning.',
    isPrimary: true,
    createdAt: subDays(today, 30),
    updatedAt: today,
  },
  {
    id: 'addr_8',
    customerId: 'cust_8',
    label: 'Gym',
    street: 'Dubai Marina',
    building: 'Marina Promenade',
    floor: 'Ground',
    apartment: 'G-15',
    area: 'Dubai Marina',
    city: 'Dubai',
    emirate: 'Dubai',
    country: 'UAE',
    coordinates: '25.0757,55.1394',
    notes: 'Cleaning supplies in storage room. Daily towel laundry area.',
    isPrimary: true,
    createdAt: subDays(today, 20),
    updatedAt: today,
  },
];

// ============================================
// BOOKINGS
// ============================================

export const mockBookings: Booking[] = [
  // Today's bookings
  {
    id: 'book_1',
    bookingNumber: 'BK-2026-00001',
    customerId: 'cust_1',
    serviceId: 'service_1',
    addressId: 'addr_1',
    scheduledDate: today,
    scheduledTime: '09:00',
    durationMinutes: 120,
    endTime: '11:00',
    status: 'CONFIRMED',
    source: 'PHONE',
    basePrice: 150,
    adjustments: 0,
    vatAmount: 7.5,
    totalPrice: 157.5,
    specialRequests: 'Focus on kitchen and bathrooms',
    internalNotes: 'VIP customer - ensure quality',
    customerRating: null,
    customerFeedback: null,
    confirmedAt: subDays(today, 2),
    startedAt: null,
    completedAt: null,
    cancelledAt: null,
    cancellationReason: null,
    createdAt: subDays(today, 3),
    updatedAt: today,
    deletedAt: null,
  },
  {
    id: 'book_2',
    bookingNumber: 'BK-2026-00002',
    customerId: 'cust_2',
    serviceId: 'service_2',
    addressId: 'addr_2',
    scheduledDate: today,
    scheduledTime: '10:00',
    durationMinutes: 240,
    endTime: '14:00',
    status: 'IN_PROGRESS',
    source: 'WEBSITE',
    basePrice: 350,
    adjustments: -25,
    vatAmount: 16.25,
    totalPrice: 341.25,
    specialRequests: 'Deep clean before guests arrive',
    internalNotes: null,
    customerRating: null,
    customerFeedback: null,
    confirmedAt: subDays(today, 1),
    startedAt: new Date(today.getTime() + 10 * 60 * 60 * 1000), // 10:00 today
    completedAt: null,
    cancelledAt: null,
    cancellationReason: null,
    createdAt: subDays(today, 5),
    updatedAt: today,
    deletedAt: null,
  },
  {
    id: 'book_3',
    bookingNumber: 'BK-2026-00003',
    customerId: 'cust_4',
    serviceId: 'service_1',
    addressId: 'addr_4',
    scheduledDate: today,
    scheduledTime: '14:00',
    durationMinutes: 150,
    endTime: '16:30',
    status: 'PENDING',
    source: 'WEBSITE',
    basePrice: 150,
    adjustments: 25,
    vatAmount: 8.75,
    totalPrice: 183.75,
    specialRequests: 'Include maid room',
    internalNotes: 'Female staff only per customer preference',
    customerRating: null,
    customerFeedback: null,
    confirmedAt: null,
    startedAt: null,
    completedAt: null,
    cancelledAt: null,
    cancellationReason: null,
    createdAt: subDays(today, 1),
    updatedAt: today,
    deletedAt: null,
  },
  {
    id: 'book_4',
    bookingNumber: 'BK-2026-00004',
    customerId: 'cust_3',
    serviceId: 'service_4',
    addressId: 'addr_3',
    scheduledDate: today,
    scheduledTime: '18:00',
    durationMinutes: 180,
    endTime: '21:00',
    status: 'CONFIRMED',
    source: 'REPEAT',
    basePrice: 225,
    adjustments: 0,
    vatAmount: 11.25,
    totalPrice: 236.25,
    specialRequests: null,
    internalNotes: 'Weekly contract - office cleaning',
    customerRating: null,
    customerFeedback: null,
    confirmedAt: subDays(today, 7),
    startedAt: null,
    completedAt: null,
    cancelledAt: null,
    cancellationReason: null,
    createdAt: subDays(today, 7),
    updatedAt: today,
    deletedAt: null,
  },
  // Tomorrow's bookings
  {
    id: 'book_5',
    bookingNumber: 'BK-2026-00005',
    customerId: 'cust_6',
    serviceId: 'service_1',
    addressId: 'addr_6',
    scheduledDate: addDays(today, 1),
    scheduledTime: '11:00',
    durationMinutes: 120,
    endTime: '13:00',
    status: 'CONFIRMED',
    source: 'WEBSITE',
    basePrice: 150,
    adjustments: 0,
    vatAmount: 7.5,
    totalPrice: 157.5,
    specialRequests: null,
    internalNotes: null,
    customerRating: null,
    customerFeedback: null,
    confirmedAt: today,
    startedAt: null,
    completedAt: null,
    cancelledAt: null,
    cancellationReason: null,
    createdAt: subDays(today, 2),
    updatedAt: today,
    deletedAt: null,
  },
  {
    id: 'book_6',
    bookingNumber: 'BK-2026-00006',
    customerId: 'cust_7',
    serviceId: 'service_2',
    addressId: 'addr_7',
    scheduledDate: addDays(today, 1),
    scheduledTime: '08:00',
    durationMinutes: 240,
    endTime: '12:00',
    status: 'CONFIRMED',
    source: 'PHONE',
    basePrice: 350,
    adjustments: 0,
    vatAmount: 17.5,
    totalPrice: 367.5,
    specialRequests: 'First deep clean for new villa',
    internalNotes: null,
    customerRating: null,
    customerFeedback: null,
    confirmedAt: today,
    startedAt: null,
    completedAt: null,
    cancelledAt: null,
    cancellationReason: null,
    createdAt: subDays(today, 1),
    updatedAt: today,
    deletedAt: null,
  },
  // Past completed bookings
  {
    id: 'book_7',
    bookingNumber: 'BK-2025-00156',
    customerId: 'cust_1',
    serviceId: 'service_1',
    addressId: 'addr_1',
    scheduledDate: subDays(today, 7),
    scheduledTime: '09:00',
    durationMinutes: 120,
    endTime: '11:00',
    status: 'COMPLETED',
    source: 'REPEAT',
    basePrice: 150,
    adjustments: 0,
    vatAmount: 7.5,
    totalPrice: 157.5,
    specialRequests: null,
    internalNotes: null,
    customerRating: 5,
    customerFeedback: 'Excellent as always!',
    confirmedAt: subDays(today, 9),
    startedAt: subDays(today, 7),
    completedAt: subDays(today, 7),
    cancelledAt: null,
    cancellationReason: null,
    createdAt: subDays(today, 10),
    updatedAt: subDays(today, 7),
    deletedAt: null,
  },
  {
    id: 'book_8',
    bookingNumber: 'BK-2025-00155',
    customerId: 'cust_5',
    serviceId: 'service_4',
    addressId: 'addr_5',
    scheduledDate: subDays(today, 5),
    scheduledTime: '19:00',
    durationMinutes: 180,
    endTime: '22:00',
    status: 'COMPLETED',
    source: 'REPEAT',
    basePrice: 225,
    adjustments: 0,
    vatAmount: 11.25,
    totalPrice: 236.25,
    specialRequests: 'Be careful with equipment',
    internalNotes: null,
    customerRating: 4,
    customerFeedback: 'Good job, minor areas missed',
    confirmedAt: subDays(today, 7),
    startedAt: subDays(today, 5),
    completedAt: subDays(today, 5),
    cancelledAt: null,
    cancellationReason: null,
    createdAt: subDays(today, 8),
    updatedAt: subDays(today, 5),
    deletedAt: null,
  },
  // Cancelled booking
  {
    id: 'book_9',
    bookingNumber: 'BK-2025-00154',
    customerId: 'cust_6',
    serviceId: 'service_3',
    addressId: 'addr_6',
    scheduledDate: subDays(today, 3),
    scheduledTime: '10:00',
    durationMinutes: 300,
    endTime: '15:00',
    status: 'CANCELLED',
    source: 'WEBSITE',
    basePrice: 500,
    adjustments: 0,
    vatAmount: 25,
    totalPrice: 525,
    specialRequests: null,
    internalNotes: null,
    customerRating: null,
    customerFeedback: null,
    confirmedAt: subDays(today, 5),
    startedAt: null,
    completedAt: null,
    cancelledAt: subDays(today, 4),
    cancellationReason: 'Customer requested cancellation - plans changed',
    createdAt: subDays(today, 6),
    updatedAt: subDays(today, 4),
    deletedAt: null,
  },
  // More upcoming bookings
  {
    id: 'book_10',
    bookingNumber: 'BK-2026-00007',
    customerId: 'cust_8',
    serviceId: 'service_4',
    addressId: 'addr_8',
    scheduledDate: addDays(today, 2),
    scheduledTime: '06:00',
    durationMinutes: 180,
    endTime: '09:00',
    status: 'CONFIRMED',
    source: 'REPEAT',
    basePrice: 225,
    adjustments: -50,
    vatAmount: 8.75,
    totalPrice: 183.75,
    specialRequests: 'Focus on equipment area and showers',
    internalNotes: 'Daily contract customer - discounted rate',
    customerRating: null,
    customerFeedback: null,
    confirmedAt: subDays(today, 30),
    startedAt: null,
    completedAt: null,
    cancelledAt: null,
    cancellationReason: null,
    createdAt: subDays(today, 30),
    updatedAt: today,
    deletedAt: null,
  },
];

// ============================================
// BOOKING STAFF ASSIGNMENTS
// ============================================

export const mockBookingStaff: BookingStaff[] = [
  { id: 'bs_1', bookingId: 'book_1', staffId: 'staff_1', isLead: true },
  { id: 'bs_2', bookingId: 'book_2', staffId: 'staff_2', isLead: true },
  { id: 'bs_3', bookingId: 'book_2', staffId: 'staff_3', isLead: false },
  { id: 'bs_4', bookingId: 'book_3', staffId: 'staff_1', isLead: true },
  { id: 'bs_5', bookingId: 'book_4', staffId: 'staff_2', isLead: true },
  { id: 'bs_6', bookingId: 'book_4', staffId: 'staff_4', isLead: false },
  { id: 'bs_7', bookingId: 'book_5', staffId: 'staff_3', isLead: true },
  { id: 'bs_8', bookingId: 'book_6', staffId: 'staff_1', isLead: true },
  { id: 'bs_9', bookingId: 'book_6', staffId: 'staff_2', isLead: false },
  { id: 'bs_10', bookingId: 'book_7', staffId: 'staff_1', isLead: true },
  { id: 'bs_11', bookingId: 'book_8', staffId: 'staff_2', isLead: true },
  { id: 'bs_12', bookingId: 'book_8', staffId: 'staff_4', isLead: false },
  { id: 'bs_13', bookingId: 'book_10', staffId: 'staff_3', isLead: true },
  { id: 'bs_14', bookingId: 'book_10', staffId: 'staff_4', isLead: false },
];

// ============================================
// INVOICES
// ============================================

export const mockInvoices: Invoice[] = [
  {
    id: 'inv_1',
    invoiceNumber: 'INV-2025-00156',
    bookingId: 'book_7',
    subtotal: 150,
    vatRate: 5,
    vatAmount: 7.5,
    discount: 0,
    total: 157.5,
    paymentStatus: 'PAID',
    paymentMethod: 'CARD',
    paidAmount: 157.5,
    paidAt: subDays(today, 7),
    issuedAt: subDays(today, 7),
    dueDate: subDays(today, 0),
    notes: null,
    createdAt: subDays(today, 7),
    updatedAt: subDays(today, 7),
  },
  {
    id: 'inv_2',
    invoiceNumber: 'INV-2025-00155',
    bookingId: 'book_8',
    subtotal: 225,
    vatRate: 5,
    vatAmount: 11.25,
    discount: 0,
    total: 236.25,
    paymentStatus: 'PAID',
    paymentMethod: 'BANK_TRANSFER',
    paidAmount: 236.25,
    paidAt: subDays(today, 4),
    issuedAt: subDays(today, 5),
    dueDate: addDays(subDays(today, 5), 7),
    notes: 'Monthly billing for commercial client',
    createdAt: subDays(today, 5),
    updatedAt: subDays(today, 4),
  },
  {
    id: 'inv_3',
    invoiceNumber: 'INV-2026-00001',
    bookingId: 'book_1',
    subtotal: 150,
    vatRate: 5,
    vatAmount: 7.5,
    discount: 0,
    total: 157.5,
    paymentStatus: 'PENDING',
    paymentMethod: null,
    paidAmount: 0,
    paidAt: null,
    issuedAt: today,
    dueDate: addDays(today, 7),
    notes: null,
    createdAt: today,
    updatedAt: today,
  },
  {
    id: 'inv_4',
    invoiceNumber: 'INV-2026-00002',
    bookingId: 'book_2',
    subtotal: 325,
    vatRate: 5,
    vatAmount: 16.25,
    discount: 25,
    total: 341.25,
    paymentStatus: 'PENDING',
    paymentMethod: null,
    paidAmount: 0,
    paidAt: null,
    issuedAt: today,
    dueDate: addDays(today, 7),
    notes: 'Loyalty discount applied',
    createdAt: today,
    updatedAt: today,
  },
];

// ============================================
// CONFLICT ALERTS
// ============================================

export const mockConflictAlerts: ConflictAlert[] = [
  {
    id: 'alert_1',
    type: 'UNDERSTAFFED',
    severity: 'MEDIUM',
    message: 'Booking BK-2026-00003 needs confirmation - staff not yet assigned',
    bookingId: 'book_3',
    staffId: undefined,
    createdAt: today,
  },
  {
    id: 'alert_2',
    type: 'AVAILABILITY',
    severity: 'LOW',
    message: 'Staff Maria Santos has limited availability on Saturday',
    bookingId: undefined,
    staffId: 'staff_2',
    createdAt: today,
  },
];

// ============================================
// DASHBOARD STATS
// ============================================

export const mockDashboardStats: DashboardStats = {
  todayBookings: 4,
  pendingBookings: 1,
  activeCrews: 2,
  completedToday: 0,
  revenueToday: 918.75,
  revenueThisMonth: 4250.50,
  newCustomers: 3,
  conflictAlerts: mockConflictAlerts,
};

// ============================================
// HELPER FUNCTIONS FOR DATA ACCESS
// ============================================

export function getBookingWithRelations(bookingId: string): Booking | null {
  const booking = mockBookings.find(b => b.id === bookingId);
  if (!booking) return null;

  return {
    ...booking,
    customer: mockCustomers.find(c => c.id === booking.customerId),
    service: mockServices.find(s => s.id === booking.serviceId),
    address: mockAddresses.find(a => a.id === booking.addressId),
    staff: mockBookingStaff
      .filter(bs => bs.bookingId === bookingId)
      .map(bs => ({
        ...bs,
        staff: mockStaff.find(s => s.id === bs.staffId),
      })),
    invoice: mockInvoices.find(i => i.bookingId === bookingId),
  };
}

export function getCustomerWithRelations(customerId: string): Customer | null {
  const customer = mockCustomers.find(c => c.id === customerId);
  if (!customer) return null;

  return {
    ...customer,
    addresses: mockAddresses.filter(a => a.customerId === customerId),
    bookings: mockBookings.filter(b => b.customerId === customerId),
  };
}

export function getStaffWithRelations(staffId: string): Staff | null {
  const staff = mockStaff.find(s => s.id === staffId);
  if (!staff) return null;

  return {
    ...staff,
    availability: mockStaffAvailability.filter(a => a.staffId === staffId),
  };
}

export function getTodayBookings(): Booking[] {
  const todayStr = format(today, 'yyyy-MM-dd');
  return mockBookings
    .filter(b => format(b.scheduledDate, 'yyyy-MM-dd') === todayStr && b.status !== 'CANCELLED')
    .map(b => getBookingWithRelations(b.id)!)
    .sort((a, b) => a.scheduledTime.localeCompare(b.scheduledTime));
}

export function getUpcomingBookings(days: number = 7): Booking[] {
  const endDate = addDays(today, days);
  return mockBookings
    .filter(b => 
      b.scheduledDate >= today && 
      b.scheduledDate <= endDate && 
      b.status !== 'CANCELLED'
    )
    .map(b => getBookingWithRelations(b.id)!)
    .sort((a, b) => a.scheduledDate.getTime() - b.scheduledDate.getTime());
}

export function getStaffBookingsForDate(staffId: string, date: Date): Booking[] {
  const dateStr = format(date, 'yyyy-MM-dd');
  const staffBookingIds = mockBookingStaff
    .filter(bs => bs.staffId === staffId)
    .map(bs => bs.bookingId);

  return mockBookings
    .filter(b => 
      staffBookingIds.includes(b.id) && 
      format(b.scheduledDate, 'yyyy-MM-dd') === dateStr &&
      b.status !== 'CANCELLED'
    )
    .map(b => getBookingWithRelations(b.id)!)
    .sort((a, b) => a.scheduledTime.localeCompare(b.scheduledTime));
}
